(function() {var implementors = {};
implementors["jsonrpc_core"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html\" title=\"struct std::ffi::c_str::CStr\">CStr</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html\" title=\"struct std::ffi::os_str::OsStr\">OsStr</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/path/struct.Path.html\" title=\"struct std::path::Path\">Path</a>",];
implementors["jsonrpc_http_server"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html\" title=\"struct std::ffi::c_str::CStr\">CStr</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html\" title=\"struct std::ffi::os_str::OsStr\">OsStr</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/path/struct.Path.html\" title=\"struct std::path::Path\">Path</a>",];
implementors["jsonrpc_ipc_server"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html\" title=\"struct std::ffi::c_str::CStr\">CStr</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html\" title=\"struct std::ffi::os_str::OsStr\">OsStr</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/path/struct.Path.html\" title=\"struct std::path::Path\">Path</a>",];
implementors["jsonrpc_macros"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html\" title=\"struct std::ffi::c_str::CStr\">CStr</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html\" title=\"struct std::ffi::os_str::OsStr\">OsStr</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/path/struct.Path.html\" title=\"struct std::path::Path\">Path</a>",];
implementors["jsonrpc_minihttp_server"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html\" title=\"struct std::ffi::c_str::CStr\">CStr</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html\" title=\"struct std::ffi::os_str::OsStr\">OsStr</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/path/struct.Path.html\" title=\"struct std::path::Path\">Path</a>",];
implementors["jsonrpc_pubsub"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html\" title=\"struct std::ffi::c_str::CStr\">CStr</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html\" title=\"struct std::ffi::os_str::OsStr\">OsStr</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/path/struct.Path.html\" title=\"struct std::path::Path\">Path</a>",];
implementors["jsonrpc_tcp_server"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html\" title=\"struct std::ffi::c_str::CStr\">CStr</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html\" title=\"struct std::ffi::os_str::OsStr\">OsStr</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/path/struct.Path.html\" title=\"struct std::path::Path\">Path</a>",];
implementors["jsonrpc_ws_server"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html\" title=\"struct std::ffi::c_str::CStr\">CStr</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html\" title=\"struct std::ffi::os_str::OsStr\">OsStr</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/path/struct.Path.html\" title=\"struct std::path::Path\">Path</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
